version: '3'

services:
  api:
    build: ./api
    command: npm run start
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - HOST=http://realworld-docker.com
      - MONGO_URI=mongodb://api-db:27017/api
    depends_on:
      - api-db

  api-db:
    image: mongo:latest
    volumes:
      - mongodb-api:/data/db

volumes:
  mongodb-api: